# Site wide configuration

title: making / learning / work
description: Adult learning project at the MIT Media Lab
logo: # 120x120 px default image used for Twitter summary card
teaser: # 400x250 px default teaser image used in image archive grid
locale: Cambirdge MA USA
url: https://mlw.media.mit.edu
# url: http://localhost:4000
baseurl:

# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title.html
markdown: kramdown
highlighter: pygments
gems:
  - jekyll-sitemap


# Site owner
owner:
  name: Juliana Nazaré
  email: juliana@media.mit.edu
  twitter: medialab
  google:
    ad-client: 
    ad-slot: 
  bio: 
  avatar: bio-photo.jpg # 160x160 px image for author byline
disqus-shortname:
# analytics :
#    provider : google
#    google : 
#        tracking_id : 'UA-38544202-3'


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
