name: Making Learning Work
url: http://learn.media.mit.edu/
markdown: redcarpet
highlighter: pygments
baseurl: /mlw
permalink: /:categories/:year/:month/:day/:title.html
comments: false
tags: true
analytics :
    provider : google
    google : 
        tracking_id : 'UA-38544202-3'