name: Making Learning Work
markdown: redcarpet
highlighter: pygments
baseurl: /mlw
permalink: /:categories/:year/:month/:day/:title.html
analytics :
  provider : google
  google : 
      tracking_id : 'UA-38544202-3'